### ISSUE TITLE
Question: What's the best way to change to another scene during narration?

### ISSUE THREAD

**Issue by metmajer** [narakeet/examples#1]
Hi @gojko,

I have a narration whose message could be emphasized by transitioning to another slide while the narration is being spoken. The challenge I'd like to solve is: how can I make a transition to the next slide without breaking the flow of the narration, i.e., introduce an unnecessary pause? Thanks!

**Comment by metmajer** [comment]
I've tried to set the pause between the two subsequent scenes to `0` via:

```
- slide: Part 1
  narration:
    - The first part of the sentence...
    - pause: 0
- slide: Part 2
  narration:
    - ...followed by the second part.
```

But this fails with the error "narration.text cannot be empty".

EDIT: I've found out that setting `pause: 0.1` gets rid of the error message, but doesn't actually shorten the transition time between the two scenes.
